version: '3.5'

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  webapi:    
    image: webapi
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:5000"                        
      "ConnectionString": "Host=postgres;Port=5432;Database=otus;UserId=postgres;Password=password"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 

  
volumes:  
  pg-data: