name: build project

on:
  push:
    branches: ["master"]

  # Позволяет запустить этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4

      - name:  Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

	  - name: Build the project
        run: dotnet publish -c Release -o ./publish
